version: "3"
services:
  app:
    container_name: metadata
    image: metadata
    environment:
      # - spring_profiles_active=local
      - MONGODB_URI=mongodb://mymongo:27017/metadata
    ports:
      - "8080:8080"
    links:
      - mymongo
  mymongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"